name: LauraLahti
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf4df'
    - '#010101'
    - '#a5a698'
    - '#029da1'
    - '#055458'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
